#!/bin/bash
# Generate a spreader-shaped workspace list: one workspace per directory, each
# with the standard agentic/git/obsidian/system tabs.
#
# Its main use is building a machine-local list of repos that should never be
# committed to this repo:
#
#   herdr-gen-spreader --scan ~/Documents/Code -o ~/.config/herdr/repos.local.yaml
#
# Usage:
#   gen-spreader.sh [--scan DIR] [--exclude a,b,c] [-o FILE] [--force] [PATH ...]
#
#   --scan DIR     add every immediate subdirectory of DIR. Defaults to
#                  ~/Documents/Code when no --scan and no PATHs are given.
#   --exclude CSV  basenames to leave out (repeatable, comma-separated)
#   -o FILE        write to FILE instead of stdout; refuses to overwrite an
#                  existing file unless --force is passed
#   PATH ...       extra directories to include, scan or not
#
# Roots are written back tilde-relative when they sit under $HOME, so the list
# stays portable between machines with different usernames.
set -uo pipefail

SCAN=""
OUT=""
FORCE=0
EXCLUDES=""
PATHS=()

while [ $# -gt 0 ]; do
  case "$1" in
    --scan)      SCAN="${2:-}"; shift ;;
    --scan=*)    SCAN="${1#--scan=}" ;;
    --exclude)   EXCLUDES="$EXCLUDES,${2:-}"; shift ;;
    --exclude=*) EXCLUDES="$EXCLUDES,${1#--exclude=}" ;;
    -o|--out)    OUT="${2:-}"; shift ;;
    --out=*)     OUT="${1#--out=}" ;;
    --force)     FORCE=1 ;;
    # Print the header comment block, stopping at the first non-comment line, so
    # the help text can grow without anyone having to fix up line numbers.
    -h|--help)   awk 'NR>1 { if ($0 !~ /^#/) exit; sub(/^# ?/, ""); print }' "$0"; exit 0 ;;
    --)          shift; while [ $# -gt 0 ]; do PATHS+=("$1"); shift; done ;;
    -*)          echo "gen-spreader: unknown flag: $1" >&2; exit 2 ;;
    *)           PATHS+=("$1") ;;
  esac
  shift
done

if [ -z "$SCAN" ] && [ "${#PATHS[@]}" -eq 0 ]; then
  SCAN="$HOME/Documents/Code"
fi

excluded() {
  case ",${EXCLUDES}," in *,"$1",*) return 0 ;; esac
  return 1
}

# Collect roots: scanned children first (alphabetical), then explicit paths.
# Deduplicated by root, since naming a path that the scan already picked up would
# otherwise emit two workspaces with the same name.
ROOTS=()
SEEN=""
add_root() {
  local root="$1"
  case "$SEEN" in *"|$root|"*) return ;; esac
  SEEN="$SEEN|$root|"
  ROOTS+=("$root")
}

if [ -n "$SCAN" ]; then
  SCAN="${SCAN/#\~/$HOME}"
  [ -d "$SCAN" ] || { echo "gen-spreader: --scan '$SCAN' is not a directory" >&2; exit 1; }
  while IFS= read -r d; do
    base=$(basename "$d")
    case "$base" in .*) continue ;; esac
    excluded "$base" && continue
    add_root "$d"
  done < <(find "$SCAN" -mindepth 1 -maxdepth 1 -type d | LC_ALL=C sort)
fi
for p in "${PATHS[@]:-}"; do
  [ -n "$p" ] || continue
  p="${p/#\~/$HOME}"
  # Normalise so ~/Documents/Code/foo and ~/Documents/Code/foo/ dedupe together.
  [ -d "$p" ] && p="$(cd "$p" && pwd)"
  excluded "$(basename "$p")" && continue
  add_root "$p"
done

if [ "${#ROOTS[@]}" -eq 0 ]; then
  echo "gen-spreader: nothing to generate (no directories matched)" >&2
  exit 1
fi

emit() {
  cat <<'HEADER'
# herdr-spreader workspace config — MACHINE-LOCAL.
#
# Generated by herdr-gen-spreader. Edit freely; regenerating overwrites it.
# `make setup-config` links this over ~/.config/herdr/spreader.yaml when it
# exists, replacing the committed list in the agentic-development repo outright.
#
# Standard layout per workspace:
#   agentic  - claude code (left pane) + codex (right pane)
#   git      - lazygit
#   obsidian - plain shell
#   system   - plain shell

workspaces:
HEADER
  local first=1
  for root in "${ROOTS[@]}"; do
    local label display
    label=$(basename "$root")
    # Tilde-relative when under $HOME, so the file survives a move between machines.
    case "$root" in
      "$HOME"/*) display="~${root#"$HOME"}" ;;
      *)         display="$root" ;;
    esac
    [ "$first" -eq 1 ] || echo
    first=0
    cat <<EOF
  - name: $label
    root: $display
    tabs:
      - label: agentic
        panes:
          - command: claude
          - command: codex
      - label: git
        panes:
          - command: lazygit
      - label: obsidian
        panes:
          - command: zsh
      - label: system
        panes:
          - command: zsh
EOF
  done
}

if [ -z "$OUT" ]; then
  emit
  exit 0
fi

OUT="${OUT/#\~/$HOME}"
if [ -e "$OUT" ] && [ "$FORCE" -ne 1 ]; then
  echo "gen-spreader: $OUT exists — pass --force to overwrite" >&2
  exit 1
fi
mkdir -p "$(dirname "$OUT")"
emit > "$OUT" || exit 1
echo "gen-spreader: wrote ${#ROOTS[@]} workspaces to $OUT" >&2
